-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE,
  full_name text NOT NULL,
  password text NOT NULL,
  role text NOT NULL DEFAULT 'Operador'::text CHECK (role = ANY (ARRAY['Administrador'::text, 'Operador'::text, 'Supervisor'::text, 'Gerente'::text, 'Consulta'::text, 'Seguridad'::text])),
  active boolean NOT NULL DEFAULT false,
  security_questions jsonb,
  reset_token text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.general_config (
  id bigint NOT NULL DEFAULT 1 CHECK (id = 1),
  institution_name text NOT NULL DEFAULT 'SteamTrack SGI'::text,
  rif text,
  address text,
  city text DEFAULT 'Caracas'::text,
  phone text,
  email text,
  logo_url text,
  hour_rate_usd numeric DEFAULT 0,
  tax_percentage numeric DEFAULT 16,
  currency_rate_usd_ves numeric,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT general_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.macollas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL UNIQUE,
  ubicacion text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT macollas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pozos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  macolla_id uuid,
  numero text NOT NULL,
  estatus text NOT NULL DEFAULT 'En espera'::text CHECK (estatus = ANY (ARRAY['En inyección'::text, 'En espera'::text, 'En mantenimiento'::text, 'En Espera de Reactivación'::text])),
  ciclo_inicio date,
  ciclo_fin date,
  vapor_acumulado_ton numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pozos_pkey PRIMARY KEY (id),
  CONSTRAINT pozos_macolla_id_fkey FOREIGN KEY (macolla_id) REFERENCES public.macollas(id)
);
CREATE TABLE public.steam_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pozo_id uuid,
  operador_id uuid,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  hora time without time zone NOT NULL DEFAULT CURRENT_TIME,
  turno text NOT NULL CHECK (turno = ANY (ARRAY['Diurno'::text, 'Nocturno'::text])),
  vapor_producido_dia numeric NOT NULL DEFAULT 0,
  horas_efectivas numeric NOT NULL DEFAULT 24 CHECK (horas_efectivas >= 0::numeric AND horas_efectivas <= 24::numeric),
  horas_perdidas numeric NOT NULL DEFAULT 0,
  causa_downtime text,
  sections_data jsonb NOT NULL,
  daily_log text,
  maintenance_checklist jsonb,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  edit_history jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT steam_reports_pkey PRIMARY KEY (id),
  CONSTRAINT steam_reports_pozo_id_fkey FOREIGN KEY (pozo_id) REFERENCES public.pozos(id),
  CONSTRAINT steam_reports_operador_id_fkey FOREIGN KEY (operador_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id text,
  old_value jsonb,
  new_value jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.registros_diarios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  titulo text,
  fecha date NOT NULL,
  hora time without time zone NOT NULL,
  turno text CHECK (turno = ANY (ARRAY['dia'::text, 'noche'::text])),
  operador_nombre text,
  presion_cabezal numeric,
  temp_cabezal numeric,
  pres_rev_prod numeric,
  temp_rev_prod numeric,
  pres_rev_sup numeric,
  temp_rev_sup numeric,
  elongacion numeric,
  tk1_nivel numeric,
  tk2_nivel numeric,
  tk3_nivel numeric,
  gv1_presion numeric,
  gv1_temp numeric,
  gv1_calidad numeric,
  gv1_flujo_agua numeric,
  gv1_flujo_gas numeric,
  gv1_inyectado numeric,
  gv3_presion numeric,
  gv3_temp numeric,
  gv3_calidad numeric,
  gv3_flujo_agua numeric,
  gv3_flujo_gas numeric,
  gv3_inyectado numeric,
  ph_alimentacion numeric,
  ph_retorno numeric,
  bitacora text,
  horas_perdidas numeric DEFAULT 0,
  causa_downtime text,
  estatus text DEFAULT 'enviado'::text,
  pozo_id uuid,
  op1_vapor_12h double precision,
  op1_total_inyectado_acum double precision,
  op3_vapor_12h double precision,
  op3_total_inyectado_acum double precision,
  total_inyectado_ambos double precision,
  tiempo_inyeccion_dias double precision,
  gv1_pres_qnt numeric,
  gv1_calidad_seteada numeric,
  gv1_calidad_equipo numeric,
  gv1_cld_cond numeric,
  gv1_pres_gas_sist numeric,
  gv1_pres_gas_gv numeric,
  gv1_consumo_gas numeric,
  gv1_ph_entrada numeric,
  gv1_ph_salida numeric,
  gv3_pres_qnt numeric,
  gv3_calidad_seteada numeric,
  gv3_calidad_equipo numeric,
  gv3_cld_cond numeric,
  gv3_pres_gas_sist numeric,
  gv3_pres_gas_gv numeric,
  gv3_consumo_gas numeric,
  gv3_ph_entrada numeric,
  gv3_ph_salida numeric,
  gv1_pres_pi_vc numeric,
  gv1_pres_pit_vc numeric,
  gv1_temp_ti_vc numeric,
  gv1_pres_vapor numeric,
  gv1_temp_vapor numeric,
  gv1_temp_tubo numeric,
  gv1_temp_chimenea numeric,
  gv3_pres_pi_vc numeric,
  gv3_pres_pit_vc numeric,
  gv3_temp_ti_vc numeric,
  gv3_pres_vapor numeric,
  gv3_temp_vapor numeric,
  gv3_temp_tubo numeric,
  gv3_temp_chimenea numeric,
  gv1_cloruro numeric,
  gv1_tds numeric,
  gv1_dureza numeric,
  gv1_o2 numeric,
  gv3_cloruro numeric,
  gv3_tds numeric,
  gv3_dureza numeric,
  gv3_o2 numeric,
  elongacion_raw text,
  CONSTRAINT registros_diarios_pkey PRIMARY KEY (id),
  CONSTRAINT registros_diarios_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT registros_diarios_pozo_id_fkey FOREIGN KEY (pozo_id) REFERENCES public.pozos(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text,
  name text NOT NULL,
  category text,
  currency text DEFAULT 'COP'::text,
  stock numeric DEFAULT 0,
  min_stock numeric DEFAULT 0,
  price_usd numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_pkey PRIMARY KEY (id)
);